### ISSUE TITLE
crash on world creation

### ISSUE THREAD

**Issue by NekoDae** [syndicate25/ProgSurv#1]
Game crashes to desktop after attempting world creation in ssp. Version 3.0.14
[latest.log](https://github.com/syndicate25/ProgSurv/files/9706659/latest.log)

**Comment by StepOnShadows** [comment]
[latest.log](https://github.com/syndicate25/ProgSurv/files/9706956/latest.log)
[2022-10-04-1.log](https://github.com/syndicate25/ProgSurv/files/9706962/2022-10-04-1.log)
[2022-10-04-2.log](https://github.com/syndicate25/ProgSurv/files/9706963/2022-10-04-2.log)
those 3 logs are from when i tried making worlds then i went back to 3.0.13 and it still did it 
[latest.log](https://github.com/syndicate25/ProgSurv/files/9706972/latest.log)

**Comment by syndicate25** [comment]
Ah yes.. this was my mistake when I distributed the pack.  I didn't remove Mine & Battlegear 2.  If you remove that mod you should be able to start a new world.  If it still crashes, post a new log, but that's the main reason it's showing right now.

You can find it in the overrides/mods folder of the pack.

**Comment by NekoDae** [comment]
Tried the manual removal, crashed upon world gen again
[latest.log](https://github.com/syndicate25/ProgSurv/files/9710083/latest.log)

**Comment by syndicate25** [comment]
Keybinding issue, another thing I've resolved in the upcoming 3.0.15 release.  It's uploading now, so give it a few hours to get approved and you should be all set.  Please test on that version and close this issue if it's working!
